use_frameworks!

platform :ios, '9.0'

target 'KCLikeButton_Example' do
  pod 'KCLikeButton', :path => '../'

  target 'KCLikeButton_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end
